### ISSUE TITLE
Next published version?

### ISSUE THREAD

**Issue by jmeas** [mattkrick/fast-bitset#1]
Allo! When do you plan to cut the next release? Need any help with it?

Also, are you on IRC/Gitter/anything? I was literally going to write this exact library last night, then I found this on `npm` just a few hours after you published v1.0.0.

**Comment by mattkrick** [comment]
Ah, thanks for the reminder, just published the new one to npm (includes a `forEach` and `getIndices`). Not really sure what else it needs, I tried to roughly give it everything the java bitset has + anything I find useful, but if you need a feature feel free to make a PR. I'm on gitter under the same name.

**Comment by jmeas** [comment]
Sweet. Thanks! Gonna close this, then. Also, I'll prob. come say :wave: on Gitter sometime.

**Comment by jmeas** [comment]
Weird, Gitter search didn't bring up ya name
