### ISSUE TITLE
Tests for new BitSet(dehydratedBitSet)

### ISSUE THREAD

**Issue by jmeas** [mattkrick/fast-bitset#4]
There aren't any tests for the alternate param in the constructor. I can add these; I just wanted to make an issue to document the task.

**Comment by mattkrick** [comment]
`clone()` uses it internally, but you're right, there should be an explicit test just for this case

**Comment by mattkrick** [comment]
fixed with 3b9a2c85c15eb66186dbcfcb7d7c45a15c0d9e03
